# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: blue-green

on:
  repository_dispatch:
    inputs: 
      inputA: 
        description: 'input A'
        required: false
      inputB: 
        description: 'input B'
        required: false

env:
  BUCKET: deocks-test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check inputA
      run: echo ${{ github.event.inputs.inputA }}
    - name: check inputB
      run: echo ${{ github.event.inputs.inputB }}      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Zip Artifacts
      run: zip -qq -r ./$GITHUB_SHA.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET/$GITHUB_SHA.zip
