# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: main2

on:
  workflow_dispatch:
    inputs: 
      inputA: 
        description: 'input A'
        required: false
      inputB: 
        description: 'input B'
        required: false
  repository_dispatch:
    inputs: 
      inputA: 
        description: 'input A'
        required: false
      inputB: 
        description: 'input B'
        required: false

env:
  BUCKET: deocks-test
  LATEST_BUILD_ARTIFACT: 'latest.zip'
  BACKUP_BUILD_ARTIFACT: 'backup.zip'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Zip Artifacts
      run: zip -qq -r ./$LATEST_BUILD_ARTIFACT .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: check s3 bucket has latest build result
      uses: tuler/s3-check-action@master
      id: check_s3
      env:
        FILE: ${{ env.LATEST_BUILD_ARTIFACT }}
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ env.BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: check env
      run: echo ${{ steps.check.outputs.exists }}
    - name: Backup last build artifacts
      if: steps.check.outputs.exists == 'true'
      run: aws s3 mv s3://$BUCKET/$LATEST_BUILD_ARTIFACT s3://$BUCKET/$BACKUP_BUILD_ARTIFACT
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$LATEST_BUILD_ARTIFACT s3://$BUCKET/$LATEST_BUILD_ARTIFACT
