# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: main

on:
  workflow_dispatch:
    inputs: 
      inputA: 
        description: 'input A'
        required: false
      inputB: 
        description: 'input B'
        required: false
  repository_dispatch:
    inputs: 
      inputA: 
        description: 'input A'
        required: false
      inputB: 
        description: 'input B'
        required: false

env:
  BUCKET: deocks-test
  HAVING_LATEST: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Zip Artifacts
      run: zip -qq -r ./latest.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Check if there is latest
      if: ${{ env.HAVING_LATEST }}
      run: echo 'yes!!'
    - name: check s3 bucket
      run: aws s3 ls s3://$BUCKET | grep latest.zip -c
    - name: Backup Last Deployment
      run: aws s3 mv s3://$BUCKET/latest.zip s3://$BUCKET/backup.zip
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./latest.zip s3://$BUCKET/latest.zip
